AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Custom resource provider for creating a SAML IDP

Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: saml_provider/
      Handler: app.lambda_handler
      Runtime: python3.6
      Role: !GetAtt FunctionRole.Arn

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref FunctionRolePolicy

  FunctionRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: GetAndPutBucketTags
            Effect: 'Allow'
            Action:
              - iam:*SAMLProvider
            Resource: '*'
Outputs:
  Function:
    Value: !GetAtt Function.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-FunctionArn'
